//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTienDien
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public string SoHoaDon { get; set; }
        public string MaDonGia { get; set; }
        public int SoLuongKW { get; set; }
    
        public virtual DonGia DonGia { get; set; }
        public virtual HoaDon HoaDon { get; set; }
    }
}
